apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: application
  labels:
    name: application
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: application
    spec:
      containers:
      - name: application
        image: ##image##
        ports:
        - containerPort: 80
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 1
          timeoutSeconds: 1
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 1
          timeoutSeconds: 1
